teaching_user:
    resource: "@TeachingUserBundle/Resources/config/routing.yml"
    prefix:   /

teaching_teacher:
    resource: "@TeachingTeacherBundle/Resources/config/routing.yml"
    prefix:   /

teaching_admin:
    resource: "@TeachingAdminBundle/Resources/config/routing.yml"
    prefix:   /

teaching_general:
    resource: "@TeachingGeneralBundle/Resources/config/routing.yml"
    prefix:   /


# For security form login and logout users
login_check:
    pattern:    /login_check
    
logout:
    pattern:    /logout