security:
    encoders:
        Teaching\GeneralBundle\Entity\Users:    sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: TeachingGeneralBundle:Users, property: username }
        
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login: 
                login_path: teaching_homepage
                check_path: login_check
            logout: 
                path: form_logout
                target: /
            

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profesor$, roles: ROLE_TEACHER }
        - { path: ^/profesor, roles: ROLE_TEACHER }
        - { path: ^/usuario$, roles: ROLE_USER }
        - { path: ^/usuario, roles: ROLE_USER }
