teaching_homepage:
    pattern:  /
    defaults: { _controller: TeachingGeneralBundle:Home:index }

exito:
    pattern: /validado
    defaults: { _controller: TeachingGeneralBundle:Home:fin }


# For security form login and logout users
login_check:
    pattern:    /login_check
    
logout:
    pattern:    /logout