teaching_homepage:
    pattern:  /
    defaults: { _controller: TeachingGeneralBundle:Home:index }

teaching_homepage_created:
    pattern:  /j
    defaults: { _controller: TeachingGeneralBundle:Home:created }

form_check:
    pattern: /login_check
    
form_logout:
    pattern: /logout
