parameters:
#    teaching_general.example.class: Teaching\GeneralBundle\Example

services:
#    teaching_general.example:
#        class: %teaching_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
