parameters:
#    teaching_teacher.example.class: Teaching\TeacherBundle\Example

services:
#    teaching_teacher.example:
#        class: %teaching_teacher.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
